# Generated by Django 4.2 on 2024-05-07 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nro_factura', models.IntegerField()),
                ('fecha', models.DateField()),
                ('nro_cuenta', models.IntegerField()),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='TipoColor',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'TipoColor',
                'verbose_name_plural': 'TipoColores',
                'db_table': 'tipo_color',
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoEntrega',
            fields=[
                ('id_estado_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'TipoEstadoEntrega',
                'verbose_name_plural': 'TipoEstadoEntregas',
                'db_table': 'tipo_estado_entrega',
            },
        ),
        migrations.CreateModel(
            name='TipoEstilo',
            fields=[
                ('id_estilo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'TipoEstilo',
                'verbose_name_plural': 'TipoEstilos',
                'db_table': 'tipo_estilo',
            },
        ),
        migrations.CreateModel(
            name='TipoMarca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'TipoMarca',
                'verbose_name_plural': 'TipoMarcas',
                'db_table': 'tipo_marca',
            },
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'TipoMaterial',
                'verbose_name_plural': 'TipoMateriales',
                'db_table': 'tipo_material',
            },
        ),
        migrations.CreateModel(
            name='TipoModoPago',
            fields=[
                ('id_modo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'TipoModoPago',
                'verbose_name_plural': 'TipoModoPagos',
                'db_table': 'tipo_modo_pago',
            },
        ),
        migrations.CreateModel(
            name='TipoRodado',
            fields=[
                ('id_rodado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'TipoRodado',
                'verbose_name_plural': 'TipoRodados',
                'db_table': 'tipo_rodado',
            },
        ),
        migrations.CreateModel(
            name='TipoRol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'TipoRol',
                'verbose_name_plural': 'TipoRoles',
                'db_table': 'tipo_rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nro_documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('id_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tiendafull.tiporol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('id_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tiendafull.tipocolor')),
                ('id_estilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tiendafull.tipoestilo')),
                ('id_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tiendafull.tipomarca')),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tiendafull.tipomaterial')),
                ('id_rodado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tiendafull.tiporodado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('nro_seguimiento', models.CharField(max_length=45)),
                ('domicilio_entrega', models.CharField(max_length=45)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('id_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tiendafull.compra')),
                ('id_estado_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tiendafull.tipoestadoentrega')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_detalle_compra', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('importe', models.FloatField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tiendafull.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tiendafull.producto')),
            ],
            options={
                'verbose_name': 'DetalleCompra',
                'verbose_name_plural': 'DetalleCompras',
                'db_table': 'detalle_compra',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tiendafull.usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_modo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tiendafull.tipomodopago'),
        ),
    ]
