# Generated by Django 4.2 on 2024-05-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiendafull', '0002_cart_alter_purchase_fecha_cartdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nro_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
