# Generated by Django 4.2 on 2024-05-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiendafull', '0003_alter_customuser_nro_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='precio_compra',
            field=models.FloatField(default=300),
            preserve_default=False,
        ),
    ]
