# Generated by Django 4.2 on 2024-05-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiendafull', '0004_purchasedetail_precio_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='id_estado_entrega',
            new_name='estado_entrega',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_estilo',
            new_name='estilo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_material',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_rodado',
            new_name='rodado',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='id_modo_pago',
            new_name='modo_pago',
        ),
    ]
