# Generated by Django 4.2 on 2024-05-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiendafull', '0005_rename_id_estado_entrega_delivery_estado_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modelo',
            field=models.CharField(default='Modelo por defecto', max_length=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
