# Generated by Django 4.2 on 2024-05-31 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiendafull', '0006_alter_product_modelo_alter_product_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_tiendafull.cart'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='fecha_estimada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
