# Generated by Django 4.2 on 2024-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tiendafull', '0007_purchase_total_alter_cartdetail_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='nro_factura',
            field=models.CharField(max_length=100),
        ),
    ]
